"""add requirements

Revision ID: 5f17cec09373
Revises: 
Create Date: 2024-02-12 01:21:46.115490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f17cec09373'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        '''create table vacancy_tracker.public.vt_requirements(
            id varchar(64) not null,
            name varchar(256) not null,
            primary key(id)
        );
        '''
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        '''
        drop table vacancy_tracker.public.vt_requirements;
        '''
    )
    # ### end Alembic commands ###
